# Generated by Django 2.2.1 on 2022-06-01 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pud_date', models.DateField()),
                ('headline', models.CharField(max_length=200)),
                ('Reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Reporter')),
            ],
        ),
    ]
